language: rust
script:
        - cargo test --verbose
        - PKG_CONFIG_ALLOW_CROSS=1 cargo build --target x86_64-unknown-linux-musl --release --verbose
rust:
        - stable
jobs:
  fast_finish: true

before_install:
        - sudo apt-get -y install musl libssl-dev musl-dev musl-tools openssl openssl-dev
        - rustup target add x86_64-unknown-linux-musl
cache: cargo

