language: rust
script:
        - cargo test --verbose
        - cargo build --target x86_64-unknown-linux-musl --release --verbose
rust:
        - stable
jobs:
  fast_finish: true

before_install:
        - sudo apt-get -y install libxml2-dev
        - rustup target add x86_64-unknown-linux-musl
cache: cargo

